name: Build

on:
  push:
    branches:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: "Lower case repo name"
        run: echo "REPOSITORY_LOWERCASE=$(tr "[A-Z]" "[a-z]" <<< ${{ github.repository }})" >> ${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Build and push image'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          pull: true
          tags: ghcr.io/${{ env.REPOSITORY_LOWERCASE }}:${{ github.sha }}
